INTERNAL_AUDIT_RESULTS = (
    ("Evet", "Uygun", "success"),
    ("Hayır", "Uygunsuz", "danger"),
    ("Kısmen", "Kısmen Uygun", "warning"),
    ("Uygulanabilir Değil", "Kapsam Dışı", "secondary"),
)


INTERNAL_AUDIT_QUESTION_BANK = [
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "4.1 - Kuruluşun Bağlamı",
        "question_text": "Kuruluşun amacını ve stratejik yönünü etkileyen iç ve dış hususlar belirlenmiş ve gözden geçiriliyor mu?",
        "evaluated_department": "Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "4.2 - İlgili Tarafların İhtiyaçları",
        "question_text": "İlgili taraflar ve bu tarafların kalite yönetim sistemiyle ilişkili beklentileri tanımlanmış mı?",
        "evaluated_department": "Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "4.3 - Kapsam",
        "question_text": "Kalite yönetim sistemi kapsamı belirlenmiş, dokümante edilmiş ve güncel tutuluyor mu?",
        "evaluated_department": "Kalite Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "4.4 - Prosesler",
        "question_text": "Kalite yönetim sistemi prosesleri, girdileri, çıktıları, sorumluları ve performans kriterleri belirlenmiş mi?",
        "evaluated_department": "Kalite Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "5.1 - Liderlik",
        "question_text": "Üst yönetim kalite yönetim sistemi için liderlik ve taahhüt gösteriyor mu?",
        "evaluated_department": "Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "5.2 - Kalite Politikası",
        "question_text": "Kalite politikası kuruluş amacıyla uyumlu, duyurulmuş ve ilgili taraflarca erişilebilir durumda mı?",
        "evaluated_department": "Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "5.3 - Roller ve Sorumluluklar",
        "question_text": "Kalite yönetim sistemi içindeki görev, yetki ve sorumluluklar tanımlanmış ve duyurulmuş mu?",
        "evaluated_department": "İnsan Kaynakları",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "6.1 - Risk ve Fırsatlar",
        "question_text": "Risk ve fırsatlar belirlenmiş, planlanan faaliyetler izleniyor ve etkinliği değerlendiriliyor mu?",
        "evaluated_department": "Kalite",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "6.2 - Kalite Hedefleri",
        "question_text": "Kalite hedeflerine ulaşmak için planlanan faaliyetler ilgili bölümlerle paylaşılmış ve takip ediliyor mu?",
        "evaluated_department": "Kalite",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "7.1 - Kaynaklar",
        "question_text": "Proseslerin performansı için gerekli kaynaklar belirlenmiş ve sağlanıyor mu?",
        "evaluated_department": "Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "7.2 - Yetkinlik",
        "question_text": "Personelin yetkinlik ihtiyaçları belirlenmiş, eğitimler planlanmış ve etkinliği değerlendiriliyor mu?",
        "evaluated_department": "İnsan Kaynakları",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "7.5 - Dokümante Edilmiş Bilgiler",
        "question_text": "Kalite yönetim sistemi kapsamındaki dokümanlar güncel, onaylı ve kullanım yerlerinde erişilebilir şekilde muhafaza ediliyor mu?",
        "evaluated_department": "Kalite",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "7.5 - Doküman Kontrolü",
        "question_text": "Dış kaynaklı dokümanlar için kriterler belirlenmiş ve güncel halleri kontrol altında tutuluyor mu?",
        "evaluated_department": "Kalite Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.1 - Operasyonel Planlama",
        "question_text": "Üretim ve hizmet sunumu için prosesler planlanmış, kontrol kriterleri belirlenmiş ve uygulanıyor mu?",
        "evaluated_department": "Üretim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.2 - Müşteri Şartları",
        "question_text": "Müşteri şartları, teklif ve sözleşme süreçlerinde eksiksiz olarak gözden geçiriliyor mu?",
        "evaluated_department": "Teklif",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.3 - Tasarım ve Geliştirme",
        "question_text": "Proje/tasarım çıktıları doğrulanıyor, değişiklikler kayıt altına alınıyor ve ilgili bölümlere duyuruluyor mu?",
        "evaluated_department": "Proje",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.4 - Dış Tedarik",
        "question_text": "Tedarikçiler belirlenmiş kriterlere göre değerlendiriliyor ve performansları izleniyor mu?",
        "evaluated_department": "Satın alma",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.5 - Üretim Kontrolü",
        "question_text": "Üretim faaliyetleri talimat, plan, kontrol formu ve uygun ekipmanlarla kontrollü şartlar altında yürütülüyor mu?",
        "evaluated_department": "Üretim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.5 - İzlenebilirlik",
        "question_text": "Ürünlerin proses boyunca tanımlanması ve izlenebilirliği sağlanıyor mu?",
        "evaluated_department": "Üretim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.5 - Müşteri Mülkiyeti",
        "question_text": "Müşteri veya dış sağlayıcı mülkiyeti korunuyor, hasar/kayıp durumları kayıt altına alınıyor mu?",
        "evaluated_department": "Şantiye",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.5 - Muhafaza",
        "question_text": "Malzeme ve ürünlerin depolama, taşıma ve sevkiyat sırasında uygunluğu korunuyor mu?",
        "evaluated_department": "Montaj",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.6 - Serbest Bırakma",
        "question_text": "Ürün kabul ve serbest bırakma kontrolleri belirlenen kriterlere göre yapılıyor ve kayıt altına alınıyor mu?",
        "evaluated_department": "Kalite",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "8.7 - Uygun Olmayan Çıktı",
        "question_text": "Uygun olmayan ürün veya hizmetler tanımlanıyor, ayrılıyor ve düzeltici işlemler kayıt altına alınıyor mu?",
        "evaluated_department": "Kalite",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "9.1 - İzleme ve Ölçme",
        "question_text": "Proseslerin performans göstergeleri tanımlanmış, ölçülüyor ve sonuçlar değerlendiriliyor mu?",
        "evaluated_department": "Kalite Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "9.1 - Müşteri Memnuniyeti",
        "question_text": "Müşteri memnuniyeti ve şikayetleri tanımlanmış proses kapsamında ele alınıyor mu?",
        "evaluated_department": "Teklif",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "9.2 - İç Tetkik",
        "question_text": "İç tetkik planı oluşturulmuş, uygulanmış ve sonuçları ilgili sorumlulara raporlanmış mı?",
        "evaluated_department": "Kalite Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "9.3 - Yönetimin Gözden Geçirmesi",
        "question_text": "Kuruluş, değişen ihtiyaç ve koşullara göre kalite yönetim sistemini gözden geçiriyor mu?",
        "evaluated_department": "Yönetim",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "10.2 - Uygunsuzluk ve Düzeltici Faaliyet",
        "question_text": "Uygunsuzluklar için kök neden analizi yapılıyor, düzeltici faaliyetler planlanıyor ve etkinliği doğrulanıyor mu?",
        "evaluated_department": "Kalite",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "Bakım Yönetimi",
        "question_text": "Kritik ekipmanlar için bakım planları oluşturulmuş ve gerçekleşen bakımlar kayıt altına alınıyor mu?",
        "evaluated_department": "Bakım",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "Finansal Süreç Kontrolü",
        "question_text": "Satın alma, fatura ve ödeme süreçleri yetkilendirme kurallarına uygun şekilde yürütülüyor mu?",
        "evaluated_department": "Finans",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "Muhasebe Kayıt Kontrolü",
        "question_text": "Muhasebe kayıtları doğrulanabilir, izlenebilir ve ilgili mevzuat gereklerine uygun şekilde tutuluyor mu?",
        "evaluated_department": "Muhasebe",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "Şantiye Uygulama Kontrolü",
        "question_text": "Şantiye uygulamalarında proje, iş güvenliği ve kalite gerekliliklerine uygunluk kontrol ediliyor mu?",
        "evaluated_department": "Şantiye",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "Montaj Süreci",
        "question_text": "Montaj faaliyetleri onaylı plan, ekipman ve kontrol kriterlerine göre yürütülüyor mu?",
        "evaluated_department": "Montaj",
    },
    {
        "standard": "ISO 9001:2015 - Kalite Yönetim Sistemi",
        "audit_topic": "Sürekli İyileştirme",
        "question_text": "Kuruluş iyileştirme fırsatlarını belirliyor, takip ediyor ve sonuçlarını değerlendiriyor mu?",
        "evaluated_department": "Kalite Yönetim",
    },
]
